Make it work from virtualenv
I'm following the "getting started" guide, but don't want to `sudo pip install` things, so am running this in a virtualenv. It doesn't work because using `shell=True`, removing it works. I don't think you actually need `shell=True` as you're just executing a command, not using redirects/pipes/etc. in the command itself.

Also, a second problem that I'm not solving in this PR, the binary it created didn't have execute rights:

```
><((("> python test.py
Your installed tdw Python module is up to date with PyPi.
Couldn't find build at /home/beyer/tdw_build/TDW/TDW.x86_64
Downloading now...
Downloaded the build.
Saved the .zip file.
Extracted the .zip file to: /home/beyer/tdw_build
Deleted the .zip file.
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    c = Controller()
  File "/home/beyer/academic/tdw/env/lib/python3.8/site-packages/tdw/controller.py", line 45, in __init__
    Controller.launch_build(display)
  File "/home/beyer/academic/tdw/env/lib/python3.8/site-packages/tdw/controller.py", line 305, in launch_build
    Popen(str(Build.BUILD_PATH.resolve()))
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/beyer/tdw_build/TDW/TDW.x86_64'
Ô.o 1 46909ms ⚡1.14 (tdw/env) (inst/go) [beyer@grimbergen:~/a/tdw 18:06:04]
><((("> mkdir ~/tdw_build
mkdir: cannot create directory ‘/home/beyer/tdw_build’: File exists
Ô.o 1 ⚡1.29 (tdw/env) (inst/go) [beyer@grimbergen:~/a/tdw 18:06:32]
><((("> ll ~/tdw_build
total 4.0K
drwxr-xr-x 3 beyer beyer 4.0K Jul 26 18:06 TDW/
:) ⚡1.10 (tdw/env) (inst/go) [beyer@grimbergen:~/a/tdw 18:06:38]
><((("> ll ~/tdw_build/TDW/
total 29M
drwxr-xr-x 6 beyer beyer 4.0K Jul 26 18:06 TDW_Data/
-rw-r--r-- 1 beyer beyer  29M Jul 26 18:06 TDW.x86_64
:) ⚡1.10 (tdw/env) (inst/go) [beyer@grimbergen:~/a/tdw 18:06:41]
><((("> chmod +x ~/tdw_build/TDW/TDW.x86_64 
:) ⚡0.78 (tdw/env) (inst/go) [beyer@grimbergen:~/a/tdw 18:07:00]
><((("> python test.py
Your installed tdw Python module is up to date with PyPi.
Found path: /home/beyer/tdw_build/TDW/TDW.x86_64
Build version 1.6.1
Unity Engine 2019.2.21f1
Python tdw module version 1.6.1
Everything is OK!
:) 4643ms ⚡0.90 (tdw/env) (inst/go) [beyer@grimbergen:~/a/tdw 18:07:11]
```